[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[docker]
symbol = " "

[elixir]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

